CREATE TABLE "User" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar,
  "last_name" varchar,
  "email" varchar UNIQUE,
  "phone" varchar,
  "password_hash" varchar,
  "registered_at" timestamp,
  "is_active" boolean,
  "role_id" int
);

CREATE TABLE "Role" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "description" text
);

CREATE TABLE "Shelter" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "phone" varchar,
  "email" varchar,
  "address_id" int
);

CREATE TABLE "Address" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "street" varchar,
  "city" varchar,
  "region" varchar,
  "postal_code" varchar,
  "country" varchar
);

CREATE TABLE "Cat" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "shelter_id" int,
  "name" varchar,
  "breed" varchar,
  "gender" varchar,
  "birth_date" date,
  "vaccinated" boolean,
  "neutered" boolean,
  "health_status" varchar,
  "available" boolean,
  "intake_date" timestamp
);

CREATE TABLE "Application" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "applicant_id" int,
  "cat_id" int,
  "submitted_at" timestamp,
  "auto_check_result" varchar,
  "notes" text
);

CREATE TABLE "Interview" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "application_id" int,
  "interviewer_id" int,
  "scheduled_at" timestamp,
  "conducted_at" timestamp,
  "result" varchar,
  "notes" text
);

CREATE TABLE "Document" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "application_id" int,
  "document_type_id" int,
  "file_path" varchar,
  "signed" boolean,
  "signed_at" timestamp
);

CREATE TABLE "DocumentType" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "description" text
);

CREATE TABLE "Adoption" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "application_id" int,
  "adoption_start_date" timestamp,
  "adoption_end_date" timestamp,
  "trial_period_end_date" timestamp,
  "finalization_date" timestamp,
  "notes" text
);

CREATE TABLE "Refusal" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "application_id" int,
  "reason_id" int,
  "staff_id" int,
  "notes" text,
  "recorded_at" timestamp
);

CREATE TABLE "RefusalReason" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar UNIQUE,
  "name" varchar,
  "description" text,
  "category" varchar
);

CREATE TABLE "AdoptionDocument" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "adoption_id" int,
  "document_id" int
);

ALTER TABLE "User" ADD FOREIGN KEY ("role_id") REFERENCES "Role" ("id");

ALTER TABLE "Shelter" ADD FOREIGN KEY ("address_id") REFERENCES "Address" ("id");

ALTER TABLE "Cat" ADD FOREIGN KEY ("shelter_id") REFERENCES "Shelter" ("id");

ALTER TABLE "Application" ADD FOREIGN KEY ("applicant_id") REFERENCES "User" ("id");

ALTER TABLE "Application" ADD FOREIGN KEY ("cat_id") REFERENCES "Cat" ("id");

ALTER TABLE "Interview" ADD FOREIGN KEY ("application_id") REFERENCES "Application" ("id");

ALTER TABLE "Interview" ADD FOREIGN KEY ("interviewer_id") REFERENCES "User" ("id");

ALTER TABLE "Document" ADD FOREIGN KEY ("application_id") REFERENCES "Application" ("id");

ALTER TABLE "Document" ADD FOREIGN KEY ("document_type_id") REFERENCES "DocumentType" ("id");

ALTER TABLE "Adoption" ADD FOREIGN KEY ("application_id") REFERENCES "Application" ("id");

ALTER TABLE "Refusal" ADD FOREIGN KEY ("application_id") REFERENCES "Application" ("id");

ALTER TABLE "Refusal" ADD FOREIGN KEY ("reason_id") REFERENCES "RefusalReason" ("id");

ALTER TABLE "Refusal" ADD FOREIGN KEY ("staff_id") REFERENCES "User" ("id");

ALTER TABLE "AdoptionDocument" ADD FOREIGN KEY ("adoption_id") REFERENCES "Adoption" ("id");

ALTER TABLE "AdoptionDocument" ADD FOREIGN KEY ("document_id") REFERENCES "Document" ("id");
